# Generated by Django 6.0.7 on 2026-07-21 14:42
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
            ],
            options={
                "verbose_name": "Banned",
                "db_table": "banned",
            },
        ),
    ]
