{{- range .Values.services  }}
{{- if .hasDeployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
      env: {{ $.Values.global.env }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        env: {{ $.Values.global.env }}
      {{- if .isPartOfConsul }}
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service: '{{ .serviceAccountName }}'
        {{- if ne .name "frontend" }}
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "5432"
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ .serviceAccountName }}
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          {{- if ne .name "password-generator" }}
          ports:
            - containerPort: {{ .containerPort }}
          {{- end }}
          env:
          {{- if eq .name "general" }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- end }}
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: DSN
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: EMAIL_FROM
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: EMAIL_PORT
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: EMAIL_HOST
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: EMAIL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: DB_HOST
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: JWT_KEY
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: AWS_STORAGE_BUCKET_NAME
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: AWS_REGION
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: SECRET_KEY
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: GROQ_API_KEY
            - name: CARTO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-aws-secrets-map
                  key: CARTO_API_KEY
          volumeMounts:
          - name: secrets-volume
            mountPath: "/mnt/secrets"
            readOnly: true
          resources:
            requests:
             cpu: "150m"
             memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          {{- if .getCheck }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .containerPort }}
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
             path: /health
             port: {{ .containerPort }}
            initialDelaySeconds: 60
            periodSeconds: 15
          {{- end }}
      volumes:
        - name: secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets-all"
{{- end }}
{{- end }}
