{{- range .Values.services  }}
{{- if .hasSecret}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  namespace: app
type: Opaque
stringData:
  DSN: '{{ .DSN }}'
  JWT_KEY: '{{ .JWT_KEY }}'
  DB_NAME: '{{ .DB_NAME }}'
  DB_USER: '{{ .DB_USER }}'
  DB_PASS: '{{ .DB_PASS }}'
  DB_HOST: '{{ .DB_HOST }}'
  SECRET_KEY: '{{ .SECRET_KEY }}'
  AWS_REGION: '{{ .AWS_REGION }}'
  AWS_STORAGE_BUCKET_NAME: '{{ .AWS_STORAGE_BUCKET_NAME }}'
  EMAIL_FROM: '{{ .EMAIL_FROM }}'
  EMAIL_PASSWORD: '{{ .EMAIL_PASSWORD }}'
  EMAIL_PORT: '{{ .EMAIL_PORT }}'
  EMAIL_HOST: '{{ .EMAIL_HOST }}'
{{- end }}
{{- end }}
