apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-all
  namespace: app
  labels:
    env: {{ .Values.global.env }}
spec:
  provider: aws

  parameters:
    usePodIdentity: "true"
    region: "eu-north-1"

    objects: |
      - objectName: "DSN"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DSN"
            objectAlias: "DSN"

      - objectName: "EMAIL_FROM"
        objectType: "secretsmanager"
        jmesPath:
          - path: "EMAIL_FROM"
            objectAlias: "EMAIL_FROM"

      - objectName: "EMAIL_PORT"
        objectType: "secretsmanager"
        jmesPath:
          - path: "EMAIL_PORT"
            objectAlias: "EMAIL_PORT"

      - objectName: "EMAIL_HOST"
        objectType: "secretsmanager"
        jmesPath:
          - path: "EMAIL_HOST"
            objectAlias: "EMAIL_HOST"

      - objectName: "EMAIL_PASSWORD"
        objectType: "secretsmanager"
        jmesPath:
          - path: "EMAIL_PASSWORD"
            objectAlias: "EMAIL_PASSWORD"

      - objectName: "DB_NAME"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_NAME"
            objectAlias: "DB_NAME"

      - objectName: "DB_USER"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_USER"
            objectAlias: "DB_USER"

      - objectName: "DB_PASS"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_PASS"
            objectAlias: "DB_PASS"

      - objectName: "DB_HOST"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_HOST"
            objectAlias: "DB_HOST"

      - objectName: "JWT_KEY"
        objectType: "secretsmanager"
        jmesPath:
          - path: "JWT_KEY"
            objectAlias: "JWT_KEY"

      - objectName: "AWS_STORAGE_BUCKET_NAME"
        objectType: "secretsmanager"
        jmesPath:
          - path: "AWS_STORAGE_BUCKET_NAME"
            objectAlias: "AWS_STORAGE_BUCKET_NAME"

      - objectName: "AWS_REGION"
        objectType: "secretsmanager"
        jmesPath:
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"

      - objectName: "SECRET_KEY"
        objectType: "secretsmanager"
        jmesPath:
          - path: "SECRET_KEY"
            objectAlias: "SECRET_KEY"

      - objectName: "GROQ_API_KEY"
        objectType: "secretsmanager"
        jmesPath:
          - path: "GROQ_API_KEY"
            objectAlias: "GROQ_API_KEY"

      - objectName: "VITE_CARTO_API_KEY"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VITE_CARTO_API_KEY"
            objectAlias: "VITE_CARTO_API_KEY"



  secretObjects:
    - secretName: app-aws-secrets-map
      type: Opaque

      data:
        - objectName: DSN
          key: DSN

        - objectName: EMAIL_FROM
          key: EMAIL_FROM

        - objectName: EMAIL_PORT
          key: EMAIL_PORT

        - objectName: EMAIL_HOST
          key: EMAIL_HOST

        - objectName: EMAIL_PASSWORD
          key: EMAIL_PASSWORD

        - objectName: DB_NAME
          key: DB_NAME

        - objectName: DB_USER
          key: DB_USER

        - objectName: DB_PASS
          key: DB_PASS

        - objectName: DB_HOST
          key: DB_HOST

        - objectName: JWT_KEY
          key: JWT_KEY

        - objectName: AWS_STORAGE_BUCKET_NAME
          key: AWS_STORAGE_BUCKET_NAME

        - objectName: AWS_REGION
          key: AWS_REGION

        - objectName: SECRET_KEY
          key: SECRET_KEY

        - objectName: GROQ_API_KEY
          key: GROQ_API_KEY

        - objectName: VITE_CARTO_API_KEY
          key: VITE_CARTO_API_KEY
