# Generated by Django 6.0.7 on 2026-07-21 14:42
# pylint: skip-file
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("agree", models.IntegerField()),
                ("disagree", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "db_table": "votes",
            },
        ),
    ]
