# Generated by Django 6.0.7 on 2026-07-22 17:16
# pylint: skip-file
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote_res",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.user",
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="votes.vote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote_res",
                "db_table": "votes_res",
            },
        ),
    ]
