# Generated by Django 6.0.7 on 2026-07-24 14:45
# pylint: skip-file
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0002_vote_res"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
