# Generated by Django 6.0.7 on 2026-07-25 11:04
# pylint: skip-file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_inquisitor"),
        ("votes", "0003_vote_time_created"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vote_res",
            new_name="VoteRes",
        ),
    ]
