# Generated by Django 6.0.7 on 2026-08-12 12:21
# pylint: disable=missing-module-docstring,missing-class-docstring,invalid-name,too-few-public-methods

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_created_at_post_image_url_post_seen_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image_url",
        ),
        migrations.AddField(
            model_name="post",
            name="image_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
