# Generated by Django 6.0.7 on 2026-07-21 14:42
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=300)),
                ("status", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "User",
                "db_table": "users",
            },
        ),
    ]
