# Generated by Django 6.0.7 on 2026-07-24 14:45
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="inquisitor",
            field=models.BooleanField(default=False),
        ),
    ]
