# Generated by Django 6.0.7 on 2026-07-27 11:35
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_inquisitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banned",
            field=models.BooleanField(default=False),
        ),
    ]
