# Generated by Django 6.0.7 on 2026-07-30 10:11
# pylint: skip-file

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_banned"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsitePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=300)),
                ("is_active", models.BooleanField()),
            ],
            options={
                "verbose_name": "Website passwords",
                "db_table": "website_passwords",
            },
        ),
    ]
