# Generated by Django 6.0.7 on 2026-08-07 07:56
# pylint: skip-file
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_websitepassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_architect",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Architect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Architect",
                "db_table": "architect",
            },
        ),
    ]
